/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { a,useSpring } from "@react-spring/three";





export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('../../../../compas1.glb')
  
  
  const handleOpen = () => {
    props.setHover(!props.hover);
  }
  
  const rotationAnimation  = useSpring({
    rotation: props.hover ? [0,0.5,0] : [0,0,0],

  });
  
  return (
    

    <a.group ref={group} {...props} dispose={null}     
    onPointerOver={(event) => handleOpen(true)}
    onPointerOut={(event) => handleOpen(false)}
    rotation={rotationAnimation.rotation}
    
    scale={1.5} position={[0.5,-1.5,-1]}>

<a.mesh>
  
      <mesh geometry={nodes.Cylinder.geometry} material={materials['big circle compas']} position={[0, 1.08, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={[0.89, 0.06, 0.89]} />
      <mesh geometry={nodes.Cylinder002.geometry} material={materials['metal top']} position={[0, 1.98, -0.01]} rotation={[-Math.PI, 0, 0]} scale={[0.44, 0.32, 0.41]} />
      <mesh geometry={nodes.Torus003.geometry} material={materials.ring} position={[-0.01, 1.96, 0.06]} rotation={[-2.17, -0.01, -0.01]} scale={[0.49, 0.41, 0.45]} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials['center thingie']} position={[0, 1.08, 0.06]} rotation={[Math.PI / 2, 0, 0]} scale={[0.69, 0.06, 0.69]} />
      <mesh geometry={nodes.Torus001.geometry} material={materials['ring thin']} position={[-0.01, 1.07, 0.01]} rotation={[Math.PI / 2, 0, 0]} scale={0.43} />
      <mesh geometry={nodes.Cone.geometry} material={materials['arrow blue ']} position={[0.17, 1.32, 0.04]} rotation={[Math.PI / 2, 0.95, -Math.PI / 2]} scale={[0.02, 0.32, 0.4]} />
      <mesh geometry={nodes.Cone001.geometry} material={materials['arrow blue']} position={[-0.19, 0.82, 0.04]} rotation={[-Math.PI / 2, -0.95, Math.PI / 2]} scale={[0.03, 0.32, 0.4]} />
      <mesh geometry={nodes.Torus006.geometry} material={materials['compas cicle']} position={[0, 1.08, -0.02]} rotation={[Math.PI / 2, 0, 0]} scale={0.6} />
      </a.mesh>

    </a.group>
  )
}

useGLTF.preload('../../../../compas1.glb')
